version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 10

workflows:
  version: 2
  flow:
    jobs:
      - build
