version: '3'

services:
    flask-app:
        build: ./flask-app
        volumes:
            - ./flask-app:/code
        ports:
            - "80:5000"
        command: python app.py

volumes:
    db-data:
